// Code generated by ent, DO NOT EDIT.

package cmdbip

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the cmdbip type in the database.
	Label = "cmdb_ip"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUser holds the string denoting the user field in the database.
	FieldUser = "user"
	// FieldDepartment holds the string denoting the department field in the database.
	FieldDepartment = "department"
	// FieldMobile holds the string denoting the mobile field in the database.
	FieldMobile = "mobile"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// FieldIP holds the string denoting the ip field in the database.
	FieldIP = "ip"
	// FieldMask holds the string denoting the mask field in the database.
	FieldMask = "mask"
	// FieldGateway holds the string denoting the gateway field in the database.
	FieldGateway = "gateway"
	// FieldOnlineTime holds the string denoting the online_time field in the database.
	FieldOnlineTime = "online_time"
	// FieldOfflineTime holds the string denoting the offline_time field in the database.
	FieldOfflineTime = "offline_time"
	// FieldIsLeisure holds the string denoting the is_leisure field in the database.
	FieldIsLeisure = "is_leisure"
	// FieldDeviceType holds the string denoting the device_type field in the database.
	FieldDeviceType = "device_type"
	// Table holds the table name of the cmdbip in the database.
	Table = "cmdb_ips"
)

// Columns holds all SQL columns for cmdbip fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUser,
	FieldDepartment,
	FieldMobile,
	FieldRemark,
	FieldIP,
	FieldMask,
	FieldGateway,
	FieldOnlineTime,
	FieldOfflineTime,
	FieldIsLeisure,
	FieldDeviceType,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// MobileValidator is a validator for the "mobile" field. It is called by the builders before save.
	MobileValidator func(string) error
	// DefaultIsLeisure holds the default value on creation for the "is_leisure" field.
	DefaultIsLeisure uint
	// DefaultDeviceType holds the default value on creation for the "device_type" field.
	DefaultDeviceType string
)

// OrderOption defines the ordering options for the CmdbIp queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUser orders the results by the user field.
func ByUser(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUser, opts...).ToFunc()
}

// ByDepartment orders the results by the department field.
func ByDepartment(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDepartment, opts...).ToFunc()
}

// ByMobile orders the results by the mobile field.
func ByMobile(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMobile, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// ByIP orders the results by the ip field.
func ByIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIP, opts...).ToFunc()
}

// ByMask orders the results by the mask field.
func ByMask(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMask, opts...).ToFunc()
}

// ByGateway orders the results by the gateway field.
func ByGateway(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGateway, opts...).ToFunc()
}

// ByOnlineTime orders the results by the online_time field.
func ByOnlineTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOnlineTime, opts...).ToFunc()
}

// ByOfflineTime orders the results by the offline_time field.
func ByOfflineTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOfflineTime, opts...).ToFunc()
}

// ByIsLeisure orders the results by the is_leisure field.
func ByIsLeisure(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsLeisure, opts...).ToFunc()
}

// ByDeviceType orders the results by the device_type field.
func ByDeviceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceType, opts...).ToFunc()
}
