// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CmdbsColumns holds the columns for the "cmdbs" table.
	CmdbsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// CmdbsTable holds the schema information for the "cmdbs" table.
	CmdbsTable = &schema.Table{
		Name:       "cmdbs",
		Columns:    CmdbsColumns,
		PrimaryKey: []*schema.Column{CmdbsColumns[0]},
	}
	// CmdbAssetsColumns holds the columns for the "cmdb_assets" table.
	CmdbAssetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time | 创建日期"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "Update Time | 修改日期"},
		{Name: "user", Type: field.TypeString, Unique: true, Comment: "用户"},
		{Name: "department", Type: field.TypeString, Comment: "部门"},
		{Name: "mobile", Type: field.TypeString, Size: 11, Comment: "联系方式"},
		{Name: "remark", Type: field.TypeString, Comment: "备注"},
		{Name: "ip", Type: field.TypeString, Unique: true},
		{Name: "mask", Type: field.TypeString},
		{Name: "gateway", Type: field.TypeString},
		{Name: "online_time", Type: field.TypeTime},
		{Name: "offline_time", Type: field.TypeTime},
		{Name: "power_status", Type: field.TypeUint, Comment: "电源状态 | 1: 开机 | 0: 关机", Default: 1},
		{Name: "is_server", Type: field.TypeUint, Comment: "是否服务器 | 1: 是 | 0: 否", Default: 1},
		{Name: "server_type", Type: field.TypeUint, Comment: "服务器类型 | 1: 物理机 | 2: 虚拟机 | 3: 容器", Default: 1},
		{Name: "server_hostname", Type: field.TypeString, Comment: "服务器主机名", Default: "localhost"},
		{Name: "server_os", Type: field.TypeString, Comment: "服务器操作系统", Default: "Linux"},
		{Name: "server_os_version", Type: field.TypeString, Comment: "服务器操作系统版本", Default: "CentOS 7.6.1810"},
		{Name: "server_os_arch", Type: field.TypeString, Comment: "服务器操作系统架构", Default: "AMD64"},
		{Name: "cpu", Type: field.TypeString, Comment: "cpu"},
		{Name: "memory", Type: field.TypeString, Comment: "内存"},
		{Name: "disk", Type: field.TypeString, Comment: "硬盘"},
		{Name: "network_speed", Type: field.TypeString, Comment: "网卡速率 | 100M | 1G | 10G | 100G", Default: "1G"},
		{Name: "device_address", Type: field.TypeString, Comment: "设备位置", Default: "机房"},
	}
	// CmdbAssetsTable holds the schema information for the "cmdb_assets" table.
	CmdbAssetsTable = &schema.Table{
		Name:       "cmdb_assets",
		Columns:    CmdbAssetsColumns,
		PrimaryKey: []*schema.Column{CmdbAssetsColumns[0]},
	}
	// CmdbIpsColumns holds the columns for the "cmdb_ips" table.
	CmdbIpsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time | 创建日期"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "Update Time | 修改日期"},
		{Name: "user", Type: field.TypeString, Unique: true, Comment: "用户"},
		{Name: "department", Type: field.TypeString, Comment: "部门"},
		{Name: "mobile", Type: field.TypeString, Size: 11, Comment: "联系方式"},
		{Name: "remark", Type: field.TypeString, Comment: "备注"},
		{Name: "ip", Type: field.TypeString, Unique: true, Comment: "IP"},
		{Name: "mask", Type: field.TypeString, Comment: "掩码"},
		{Name: "gateway", Type: field.TypeString, Comment: "网关"},
		{Name: "online_time", Type: field.TypeTime, Comment: "上线时间"},
		{Name: "offline_time", Type: field.TypeTime, Comment: "下线时间"},
		{Name: "is_leisure", Type: field.TypeUint, Comment: "是否空闲 | 1: 空闲 | 0: 使用中", Default: 1},
		{Name: "device_type", Type: field.TypeString, Comment: "设备类型 | 服务器 | 网络设备 | 存储设备 | PC | 其他", Default: ""},
	}
	// CmdbIpsTable holds the schema information for the "cmdb_ips" table.
	CmdbIpsTable = &schema.Table{
		Name:       "cmdb_ips",
		Columns:    CmdbIpsColumns,
		PrimaryKey: []*schema.Column{CmdbIpsColumns[0]},
	}
	// CmdbIPUsersColumns holds the columns for the "cmdb_ip_users" table.
	CmdbIPUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Comment: "Status 1: normal 2: ban | 状态 1 正常 2 禁用", Default: 1},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time | 创建日期"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "Update Time | 修改日期"},
		{Name: "user", Type: field.TypeString, Unique: true, Comment: "用户"},
		{Name: "department", Type: field.TypeString, Comment: "部门"},
		{Name: "mobile", Type: field.TypeString, Size: 11, Comment: "联系方式"},
		{Name: "remark", Type: field.TypeString, Comment: "备注"},
	}
	// CmdbIPUsersTable holds the schema information for the "cmdb_ip_users" table.
	CmdbIPUsersTable = &schema.Table{
		Name:       "cmdb_ip_users",
		Columns:    CmdbIPUsersColumns,
		PrimaryKey: []*schema.Column{CmdbIPUsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CmdbsTable,
		CmdbAssetsTable,
		CmdbIpsTable,
		CmdbIPUsersTable,
	}
)

func init() {
}
