// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/liuzw3018/simple-admin-cmdb-rpc/ent/cmdbassets"
	"github.com/liuzw3018/simple-admin-cmdb-rpc/ent/predicate"
)

// CmdbAssetsQuery is the builder for querying CmdbAssets entities.
type CmdbAssetsQuery struct {
	config
	ctx        *QueryContext
	order      []cmdbassets.OrderOption
	inters     []Interceptor
	predicates []predicate.CmdbAssets
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CmdbAssetsQuery builder.
func (caq *CmdbAssetsQuery) Where(ps ...predicate.CmdbAssets) *CmdbAssetsQuery {
	caq.predicates = append(caq.predicates, ps...)
	return caq
}

// Limit the number of records to be returned by this query.
func (caq *CmdbAssetsQuery) Limit(limit int) *CmdbAssetsQuery {
	caq.ctx.Limit = &limit
	return caq
}

// Offset to start from.
func (caq *CmdbAssetsQuery) Offset(offset int) *CmdbAssetsQuery {
	caq.ctx.Offset = &offset
	return caq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (caq *CmdbAssetsQuery) Unique(unique bool) *CmdbAssetsQuery {
	caq.ctx.Unique = &unique
	return caq
}

// Order specifies how the records should be ordered.
func (caq *CmdbAssetsQuery) Order(o ...cmdbassets.OrderOption) *CmdbAssetsQuery {
	caq.order = append(caq.order, o...)
	return caq
}

// First returns the first CmdbAssets entity from the query.
// Returns a *NotFoundError when no CmdbAssets was found.
func (caq *CmdbAssetsQuery) First(ctx context.Context) (*CmdbAssets, error) {
	nodes, err := caq.Limit(1).All(setContextOp(ctx, caq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{cmdbassets.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (caq *CmdbAssetsQuery) FirstX(ctx context.Context) *CmdbAssets {
	node, err := caq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CmdbAssets ID from the query.
// Returns a *NotFoundError when no CmdbAssets ID was found.
func (caq *CmdbAssetsQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = caq.Limit(1).IDs(setContextOp(ctx, caq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{cmdbassets.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (caq *CmdbAssetsQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := caq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CmdbAssets entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CmdbAssets entity is found.
// Returns a *NotFoundError when no CmdbAssets entities are found.
func (caq *CmdbAssetsQuery) Only(ctx context.Context) (*CmdbAssets, error) {
	nodes, err := caq.Limit(2).All(setContextOp(ctx, caq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{cmdbassets.Label}
	default:
		return nil, &NotSingularError{cmdbassets.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (caq *CmdbAssetsQuery) OnlyX(ctx context.Context) *CmdbAssets {
	node, err := caq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CmdbAssets ID in the query.
// Returns a *NotSingularError when more than one CmdbAssets ID is found.
// Returns a *NotFoundError when no entities are found.
func (caq *CmdbAssetsQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = caq.Limit(2).IDs(setContextOp(ctx, caq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{cmdbassets.Label}
	default:
		err = &NotSingularError{cmdbassets.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (caq *CmdbAssetsQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := caq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CmdbAssetsSlice.
func (caq *CmdbAssetsQuery) All(ctx context.Context) ([]*CmdbAssets, error) {
	ctx = setContextOp(ctx, caq.ctx, "All")
	if err := caq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CmdbAssets, *CmdbAssetsQuery]()
	return withInterceptors[[]*CmdbAssets](ctx, caq, qr, caq.inters)
}

// AllX is like All, but panics if an error occurs.
func (caq *CmdbAssetsQuery) AllX(ctx context.Context) []*CmdbAssets {
	nodes, err := caq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CmdbAssets IDs.
func (caq *CmdbAssetsQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if caq.ctx.Unique == nil && caq.path != nil {
		caq.Unique(true)
	}
	ctx = setContextOp(ctx, caq.ctx, "IDs")
	if err = caq.Select(cmdbassets.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (caq *CmdbAssetsQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := caq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (caq *CmdbAssetsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, caq.ctx, "Count")
	if err := caq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, caq, querierCount[*CmdbAssetsQuery](), caq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (caq *CmdbAssetsQuery) CountX(ctx context.Context) int {
	count, err := caq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (caq *CmdbAssetsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, caq.ctx, "Exist")
	switch _, err := caq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (caq *CmdbAssetsQuery) ExistX(ctx context.Context) bool {
	exist, err := caq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CmdbAssetsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (caq *CmdbAssetsQuery) Clone() *CmdbAssetsQuery {
	if caq == nil {
		return nil
	}
	return &CmdbAssetsQuery{
		config:     caq.config,
		ctx:        caq.ctx.Clone(),
		order:      append([]cmdbassets.OrderOption{}, caq.order...),
		inters:     append([]Interceptor{}, caq.inters...),
		predicates: append([]predicate.CmdbAssets{}, caq.predicates...),
		// clone intermediate query.
		sql:  caq.sql.Clone(),
		path: caq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CmdbAssets.Query().
//		GroupBy(cmdbassets.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (caq *CmdbAssetsQuery) GroupBy(field string, fields ...string) *CmdbAssetsGroupBy {
	caq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CmdbAssetsGroupBy{build: caq}
	grbuild.flds = &caq.ctx.Fields
	grbuild.label = cmdbassets.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.CmdbAssets.Query().
//		Select(cmdbassets.FieldCreatedAt).
//		Scan(ctx, &v)
func (caq *CmdbAssetsQuery) Select(fields ...string) *CmdbAssetsSelect {
	caq.ctx.Fields = append(caq.ctx.Fields, fields...)
	sbuild := &CmdbAssetsSelect{CmdbAssetsQuery: caq}
	sbuild.label = cmdbassets.Label
	sbuild.flds, sbuild.scan = &caq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CmdbAssetsSelect configured with the given aggregations.
func (caq *CmdbAssetsQuery) Aggregate(fns ...AggregateFunc) *CmdbAssetsSelect {
	return caq.Select().Aggregate(fns...)
}

func (caq *CmdbAssetsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range caq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, caq); err != nil {
				return err
			}
		}
	}
	for _, f := range caq.ctx.Fields {
		if !cmdbassets.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if caq.path != nil {
		prev, err := caq.path(ctx)
		if err != nil {
			return err
		}
		caq.sql = prev
	}
	return nil
}

func (caq *CmdbAssetsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CmdbAssets, error) {
	var (
		nodes = []*CmdbAssets{}
		_spec = caq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CmdbAssets).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CmdbAssets{config: caq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, caq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (caq *CmdbAssetsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := caq.querySpec()
	_spec.Node.Columns = caq.ctx.Fields
	if len(caq.ctx.Fields) > 0 {
		_spec.Unique = caq.ctx.Unique != nil && *caq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, caq.driver, _spec)
}

func (caq *CmdbAssetsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(cmdbassets.Table, cmdbassets.Columns, sqlgraph.NewFieldSpec(cmdbassets.FieldID, field.TypeUint64))
	_spec.From = caq.sql
	if unique := caq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if caq.path != nil {
		_spec.Unique = true
	}
	if fields := caq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cmdbassets.FieldID)
		for i := range fields {
			if fields[i] != cmdbassets.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := caq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := caq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := caq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := caq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (caq *CmdbAssetsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(caq.driver.Dialect())
	t1 := builder.Table(cmdbassets.Table)
	columns := caq.ctx.Fields
	if len(columns) == 0 {
		columns = cmdbassets.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if caq.sql != nil {
		selector = caq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if caq.ctx.Unique != nil && *caq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range caq.predicates {
		p(selector)
	}
	for _, p := range caq.order {
		p(selector)
	}
	if offset := caq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := caq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CmdbAssetsGroupBy is the group-by builder for CmdbAssets entities.
type CmdbAssetsGroupBy struct {
	selector
	build *CmdbAssetsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cagb *CmdbAssetsGroupBy) Aggregate(fns ...AggregateFunc) *CmdbAssetsGroupBy {
	cagb.fns = append(cagb.fns, fns...)
	return cagb
}

// Scan applies the selector query and scans the result into the given value.
func (cagb *CmdbAssetsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cagb.build.ctx, "GroupBy")
	if err := cagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CmdbAssetsQuery, *CmdbAssetsGroupBy](ctx, cagb.build, cagb, cagb.build.inters, v)
}

func (cagb *CmdbAssetsGroupBy) sqlScan(ctx context.Context, root *CmdbAssetsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cagb.fns))
	for _, fn := range cagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cagb.flds)+len(cagb.fns))
		for _, f := range *cagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CmdbAssetsSelect is the builder for selecting fields of CmdbAssets entities.
type CmdbAssetsSelect struct {
	*CmdbAssetsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cas *CmdbAssetsSelect) Aggregate(fns ...AggregateFunc) *CmdbAssetsSelect {
	cas.fns = append(cas.fns, fns...)
	return cas
}

// Scan applies the selector query and scans the result into the given value.
func (cas *CmdbAssetsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cas.ctx, "Select")
	if err := cas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CmdbAssetsQuery, *CmdbAssetsSelect](ctx, cas.CmdbAssetsQuery, cas, cas.inters, v)
}

func (cas *CmdbAssetsSelect) sqlScan(ctx context.Context, root *CmdbAssetsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cas.fns))
	for _, fn := range cas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
