// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/liuzw3018/simple-admin-cmdb-rpc/ent/cmdbassets"
	"github.com/liuzw3018/simple-admin-cmdb-rpc/ent/predicate"
)

// CmdbAssetsDelete is the builder for deleting a CmdbAssets entity.
type CmdbAssetsDelete struct {
	config
	hooks    []Hook
	mutation *CmdbAssetsMutation
}

// Where appends a list predicates to the CmdbAssetsDelete builder.
func (cad *CmdbAssetsDelete) Where(ps ...predicate.CmdbAssets) *CmdbAssetsDelete {
	cad.mutation.Where(ps...)
	return cad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cad *CmdbAssetsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, cad.sqlExec, cad.mutation, cad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (cad *CmdbAssetsDelete) ExecX(ctx context.Context) int {
	n, err := cad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cad *CmdbAssetsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(cmdbassets.Table, sqlgraph.NewFieldSpec(cmdbassets.FieldID, field.TypeUint64))
	if ps := cad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	cad.mutation.done = true
	return affected, err
}

// CmdbAssetsDeleteOne is the builder for deleting a single CmdbAssets entity.
type CmdbAssetsDeleteOne struct {
	cad *CmdbAssetsDelete
}

// Where appends a list predicates to the CmdbAssetsDelete builder.
func (cado *CmdbAssetsDeleteOne) Where(ps ...predicate.CmdbAssets) *CmdbAssetsDeleteOne {
	cado.cad.mutation.Where(ps...)
	return cado
}

// Exec executes the deletion query.
func (cado *CmdbAssetsDeleteOne) Exec(ctx context.Context) error {
	n, err := cado.cad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{cmdbassets.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cado *CmdbAssetsDeleteOne) ExecX(ctx context.Context) {
	if err := cado.Exec(ctx); err != nil {
		panic(err)
	}
}
