// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/liuzw3018/simple-admin-cmdb-rpc/ent/cmdbassets"
	"github.com/liuzw3018/simple-admin-cmdb-rpc/ent/cmdbip"
	"github.com/liuzw3018/simple-admin-cmdb-rpc/ent/cmdbipuser"
	"github.com/liuzw3018/simple-admin-cmdb-rpc/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	cmdbassetsMixin := schema.CmdbAssets{}.Mixin()
	cmdbassetsMixinFields0 := cmdbassetsMixin[0].Fields()
	_ = cmdbassetsMixinFields0
	cmdbassetsFields := schema.CmdbAssets{}.Fields()
	_ = cmdbassetsFields
	// cmdbassetsDescCreatedAt is the schema descriptor for created_at field.
	cmdbassetsDescCreatedAt := cmdbassetsMixinFields0[1].Descriptor()
	// cmdbassets.DefaultCreatedAt holds the default value on creation for the created_at field.
	cmdbassets.DefaultCreatedAt = cmdbassetsDescCreatedAt.Default.(func() time.Time)
	// cmdbassetsDescUpdatedAt is the schema descriptor for updated_at field.
	cmdbassetsDescUpdatedAt := cmdbassetsMixinFields0[2].Descriptor()
	// cmdbassets.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	cmdbassets.DefaultUpdatedAt = cmdbassetsDescUpdatedAt.Default.(func() time.Time)
	// cmdbassets.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	cmdbassets.UpdateDefaultUpdatedAt = cmdbassetsDescUpdatedAt.UpdateDefault.(func() time.Time)
	// cmdbassetsDescMobile is the schema descriptor for mobile field.
	cmdbassetsDescMobile := cmdbassetsMixinFields0[5].Descriptor()
	// cmdbassets.MobileValidator is a validator for the "mobile" field. It is called by the builders before save.
	cmdbassets.MobileValidator = func() func(string) error {
		validators := cmdbassetsDescMobile.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(mobile string) error {
			for _, fn := range fns {
				if err := fn(mobile); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// cmdbassetsDescPowerStatus is the schema descriptor for power_status field.
	cmdbassetsDescPowerStatus := cmdbassetsFields[5].Descriptor()
	// cmdbassets.DefaultPowerStatus holds the default value on creation for the power_status field.
	cmdbassets.DefaultPowerStatus = cmdbassetsDescPowerStatus.Default.(uint)
	// cmdbassetsDescIsServer is the schema descriptor for is_server field.
	cmdbassetsDescIsServer := cmdbassetsFields[6].Descriptor()
	// cmdbassets.DefaultIsServer holds the default value on creation for the is_server field.
	cmdbassets.DefaultIsServer = cmdbassetsDescIsServer.Default.(uint)
	// cmdbassetsDescServerType is the schema descriptor for server_type field.
	cmdbassetsDescServerType := cmdbassetsFields[7].Descriptor()
	// cmdbassets.DefaultServerType holds the default value on creation for the server_type field.
	cmdbassets.DefaultServerType = cmdbassetsDescServerType.Default.(uint)
	// cmdbassetsDescServerHostname is the schema descriptor for server_hostname field.
	cmdbassetsDescServerHostname := cmdbassetsFields[8].Descriptor()
	// cmdbassets.DefaultServerHostname holds the default value on creation for the server_hostname field.
	cmdbassets.DefaultServerHostname = cmdbassetsDescServerHostname.Default.(string)
	// cmdbassetsDescServerOs is the schema descriptor for server_os field.
	cmdbassetsDescServerOs := cmdbassetsFields[9].Descriptor()
	// cmdbassets.DefaultServerOs holds the default value on creation for the server_os field.
	cmdbassets.DefaultServerOs = cmdbassetsDescServerOs.Default.(string)
	// cmdbassetsDescServerOsVersion is the schema descriptor for server_os_version field.
	cmdbassetsDescServerOsVersion := cmdbassetsFields[10].Descriptor()
	// cmdbassets.DefaultServerOsVersion holds the default value on creation for the server_os_version field.
	cmdbassets.DefaultServerOsVersion = cmdbassetsDescServerOsVersion.Default.(string)
	// cmdbassetsDescServerOsArch is the schema descriptor for server_os_arch field.
	cmdbassetsDescServerOsArch := cmdbassetsFields[11].Descriptor()
	// cmdbassets.DefaultServerOsArch holds the default value on creation for the server_os_arch field.
	cmdbassets.DefaultServerOsArch = cmdbassetsDescServerOsArch.Default.(string)
	// cmdbassetsDescNetworkSpeed is the schema descriptor for NetworkSpeed field.
	cmdbassetsDescNetworkSpeed := cmdbassetsFields[15].Descriptor()
	// cmdbassets.DefaultNetworkSpeed holds the default value on creation for the NetworkSpeed field.
	cmdbassets.DefaultNetworkSpeed = cmdbassetsDescNetworkSpeed.Default.(string)
	// cmdbassetsDescDeviceAddress is the schema descriptor for device_address field.
	cmdbassetsDescDeviceAddress := cmdbassetsFields[16].Descriptor()
	// cmdbassets.DefaultDeviceAddress holds the default value on creation for the device_address field.
	cmdbassets.DefaultDeviceAddress = cmdbassetsDescDeviceAddress.Default.(string)
	cmdbipMixin := schema.CmdbIp{}.Mixin()
	cmdbipMixinFields0 := cmdbipMixin[0].Fields()
	_ = cmdbipMixinFields0
	cmdbipFields := schema.CmdbIp{}.Fields()
	_ = cmdbipFields
	// cmdbipDescCreatedAt is the schema descriptor for created_at field.
	cmdbipDescCreatedAt := cmdbipMixinFields0[1].Descriptor()
	// cmdbip.DefaultCreatedAt holds the default value on creation for the created_at field.
	cmdbip.DefaultCreatedAt = cmdbipDescCreatedAt.Default.(func() time.Time)
	// cmdbipDescUpdatedAt is the schema descriptor for updated_at field.
	cmdbipDescUpdatedAt := cmdbipMixinFields0[2].Descriptor()
	// cmdbip.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	cmdbip.DefaultUpdatedAt = cmdbipDescUpdatedAt.Default.(func() time.Time)
	// cmdbip.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	cmdbip.UpdateDefaultUpdatedAt = cmdbipDescUpdatedAt.UpdateDefault.(func() time.Time)
	// cmdbipDescMobile is the schema descriptor for mobile field.
	cmdbipDescMobile := cmdbipMixinFields0[5].Descriptor()
	// cmdbip.MobileValidator is a validator for the "mobile" field. It is called by the builders before save.
	cmdbip.MobileValidator = func() func(string) error {
		validators := cmdbipDescMobile.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(mobile string) error {
			for _, fn := range fns {
				if err := fn(mobile); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// cmdbipDescIsLeisure is the schema descriptor for is_leisure field.
	cmdbipDescIsLeisure := cmdbipFields[5].Descriptor()
	// cmdbip.DefaultIsLeisure holds the default value on creation for the is_leisure field.
	cmdbip.DefaultIsLeisure = cmdbipDescIsLeisure.Default.(uint)
	// cmdbipDescDeviceType is the schema descriptor for device_type field.
	cmdbipDescDeviceType := cmdbipFields[6].Descriptor()
	// cmdbip.DefaultDeviceType holds the default value on creation for the device_type field.
	cmdbip.DefaultDeviceType = cmdbipDescDeviceType.Default.(string)
	cmdbipuserMixin := schema.CmdbIpUser{}.Mixin()
	cmdbipuserMixinFields0 := cmdbipuserMixin[0].Fields()
	_ = cmdbipuserMixinFields0
	cmdbipuserFields := schema.CmdbIpUser{}.Fields()
	_ = cmdbipuserFields
	// cmdbipuserDescStatus is the schema descriptor for status field.
	cmdbipuserDescStatus := cmdbipuserMixinFields0[0].Descriptor()
	// cmdbipuser.DefaultStatus holds the default value on creation for the status field.
	cmdbipuser.DefaultStatus = cmdbipuserDescStatus.Default.(uint8)
	// cmdbipuserDescCreatedAt is the schema descriptor for created_at field.
	cmdbipuserDescCreatedAt := cmdbipuserFields[1].Descriptor()
	// cmdbipuser.DefaultCreatedAt holds the default value on creation for the created_at field.
	cmdbipuser.DefaultCreatedAt = cmdbipuserDescCreatedAt.Default.(func() time.Time)
	// cmdbipuserDescUpdatedAt is the schema descriptor for updated_at field.
	cmdbipuserDescUpdatedAt := cmdbipuserFields[2].Descriptor()
	// cmdbipuser.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	cmdbipuser.DefaultUpdatedAt = cmdbipuserDescUpdatedAt.Default.(func() time.Time)
	// cmdbipuser.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	cmdbipuser.UpdateDefaultUpdatedAt = cmdbipuserDescUpdatedAt.UpdateDefault.(func() time.Time)
	// cmdbipuserDescMobile is the schema descriptor for mobile field.
	cmdbipuserDescMobile := cmdbipuserFields[5].Descriptor()
	// cmdbipuser.MobileValidator is a validator for the "mobile" field. It is called by the builders before save.
	cmdbipuser.MobileValidator = func() func(string) error {
		validators := cmdbipuserDescMobile.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(mobile string) error {
			for _, fn := range fns {
				if err := fn(mobile); err != nil {
					return err
				}
			}
			return nil
		}
	}()
}
