// Code generated by ent, DO NOT EDIT.

package ent

import "time"

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdate) SetNotNilUpdatedAt(value *time.Time) *CmdbAssetsUpdate {
	if value != nil {
		return ca.SetUpdatedAt(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdateOne) SetNotNilUpdatedAt(value *time.Time) *CmdbAssetsUpdateOne {
	if value != nil {
		return ca.SetUpdatedAt(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsCreate) SetNotNilUpdatedAt(value *time.Time) *CmdbAssetsCreate {
	if value != nil {
		return ca.SetUpdatedAt(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdate) SetNotNilUser(value *string) *CmdbAssetsUpdate {
	if value != nil {
		return ca.SetUser(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdateOne) SetNotNilUser(value *string) *CmdbAssetsUpdateOne {
	if value != nil {
		return ca.SetUser(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsCreate) SetNotNilUser(value *string) *CmdbAssetsCreate {
	if value != nil {
		return ca.SetUser(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdate) SetNotNilDepartment(value *string) *CmdbAssetsUpdate {
	if value != nil {
		return ca.SetDepartment(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdateOne) SetNotNilDepartment(value *string) *CmdbAssetsUpdateOne {
	if value != nil {
		return ca.SetDepartment(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsCreate) SetNotNilDepartment(value *string) *CmdbAssetsCreate {
	if value != nil {
		return ca.SetDepartment(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdate) SetNotNilMobile(value *string) *CmdbAssetsUpdate {
	if value != nil {
		return ca.SetMobile(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdateOne) SetNotNilMobile(value *string) *CmdbAssetsUpdateOne {
	if value != nil {
		return ca.SetMobile(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsCreate) SetNotNilMobile(value *string) *CmdbAssetsCreate {
	if value != nil {
		return ca.SetMobile(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdate) SetNotNilRemark(value *string) *CmdbAssetsUpdate {
	if value != nil {
		return ca.SetRemark(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdateOne) SetNotNilRemark(value *string) *CmdbAssetsUpdateOne {
	if value != nil {
		return ca.SetRemark(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsCreate) SetNotNilRemark(value *string) *CmdbAssetsCreate {
	if value != nil {
		return ca.SetRemark(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdate) SetNotNilIP(value *string) *CmdbAssetsUpdate {
	if value != nil {
		return ca.SetIP(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdateOne) SetNotNilIP(value *string) *CmdbAssetsUpdateOne {
	if value != nil {
		return ca.SetIP(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsCreate) SetNotNilIP(value *string) *CmdbAssetsCreate {
	if value != nil {
		return ca.SetIP(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdate) SetNotNilMask(value *string) *CmdbAssetsUpdate {
	if value != nil {
		return ca.SetMask(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdateOne) SetNotNilMask(value *string) *CmdbAssetsUpdateOne {
	if value != nil {
		return ca.SetMask(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsCreate) SetNotNilMask(value *string) *CmdbAssetsCreate {
	if value != nil {
		return ca.SetMask(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdate) SetNotNilGateway(value *string) *CmdbAssetsUpdate {
	if value != nil {
		return ca.SetGateway(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdateOne) SetNotNilGateway(value *string) *CmdbAssetsUpdateOne {
	if value != nil {
		return ca.SetGateway(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsCreate) SetNotNilGateway(value *string) *CmdbAssetsCreate {
	if value != nil {
		return ca.SetGateway(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdate) SetNotNilOnlineTime(value *time.Time) *CmdbAssetsUpdate {
	if value != nil {
		return ca.SetOnlineTime(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdateOne) SetNotNilOnlineTime(value *time.Time) *CmdbAssetsUpdateOne {
	if value != nil {
		return ca.SetOnlineTime(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsCreate) SetNotNilOnlineTime(value *time.Time) *CmdbAssetsCreate {
	if value != nil {
		return ca.SetOnlineTime(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdate) SetNotNilOfflineTime(value *time.Time) *CmdbAssetsUpdate {
	if value != nil {
		return ca.SetOfflineTime(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdateOne) SetNotNilOfflineTime(value *time.Time) *CmdbAssetsUpdateOne {
	if value != nil {
		return ca.SetOfflineTime(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsCreate) SetNotNilOfflineTime(value *time.Time) *CmdbAssetsCreate {
	if value != nil {
		return ca.SetOfflineTime(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdate) SetNotNilPowerStatus(value *uint) *CmdbAssetsUpdate {
	if value != nil {
		return ca.SetPowerStatus(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdateOne) SetNotNilPowerStatus(value *uint) *CmdbAssetsUpdateOne {
	if value != nil {
		return ca.SetPowerStatus(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsCreate) SetNotNilPowerStatus(value *uint) *CmdbAssetsCreate {
	if value != nil {
		return ca.SetPowerStatus(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdate) SetNotNilIsServer(value *uint) *CmdbAssetsUpdate {
	if value != nil {
		return ca.SetIsServer(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdateOne) SetNotNilIsServer(value *uint) *CmdbAssetsUpdateOne {
	if value != nil {
		return ca.SetIsServer(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsCreate) SetNotNilIsServer(value *uint) *CmdbAssetsCreate {
	if value != nil {
		return ca.SetIsServer(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdate) SetNotNilServerType(value *uint) *CmdbAssetsUpdate {
	if value != nil {
		return ca.SetServerType(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdateOne) SetNotNilServerType(value *uint) *CmdbAssetsUpdateOne {
	if value != nil {
		return ca.SetServerType(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsCreate) SetNotNilServerType(value *uint) *CmdbAssetsCreate {
	if value != nil {
		return ca.SetServerType(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdate) SetNotNilServerHostname(value *string) *CmdbAssetsUpdate {
	if value != nil {
		return ca.SetServerHostname(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdateOne) SetNotNilServerHostname(value *string) *CmdbAssetsUpdateOne {
	if value != nil {
		return ca.SetServerHostname(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsCreate) SetNotNilServerHostname(value *string) *CmdbAssetsCreate {
	if value != nil {
		return ca.SetServerHostname(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdate) SetNotNilServerOs(value *string) *CmdbAssetsUpdate {
	if value != nil {
		return ca.SetServerOs(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdateOne) SetNotNilServerOs(value *string) *CmdbAssetsUpdateOne {
	if value != nil {
		return ca.SetServerOs(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsCreate) SetNotNilServerOs(value *string) *CmdbAssetsCreate {
	if value != nil {
		return ca.SetServerOs(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdate) SetNotNilServerOsVersion(value *string) *CmdbAssetsUpdate {
	if value != nil {
		return ca.SetServerOsVersion(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdateOne) SetNotNilServerOsVersion(value *string) *CmdbAssetsUpdateOne {
	if value != nil {
		return ca.SetServerOsVersion(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsCreate) SetNotNilServerOsVersion(value *string) *CmdbAssetsCreate {
	if value != nil {
		return ca.SetServerOsVersion(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdate) SetNotNilServerOsArch(value *string) *CmdbAssetsUpdate {
	if value != nil {
		return ca.SetServerOsArch(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdateOne) SetNotNilServerOsArch(value *string) *CmdbAssetsUpdateOne {
	if value != nil {
		return ca.SetServerOsArch(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsCreate) SetNotNilServerOsArch(value *string) *CmdbAssetsCreate {
	if value != nil {
		return ca.SetServerOsArch(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdate) SetNotNilCPU(value *string) *CmdbAssetsUpdate {
	if value != nil {
		return ca.SetCPU(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdateOne) SetNotNilCPU(value *string) *CmdbAssetsUpdateOne {
	if value != nil {
		return ca.SetCPU(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsCreate) SetNotNilCPU(value *string) *CmdbAssetsCreate {
	if value != nil {
		return ca.SetCPU(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdate) SetNotNilMemory(value *string) *CmdbAssetsUpdate {
	if value != nil {
		return ca.SetMemory(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdateOne) SetNotNilMemory(value *string) *CmdbAssetsUpdateOne {
	if value != nil {
		return ca.SetMemory(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsCreate) SetNotNilMemory(value *string) *CmdbAssetsCreate {
	if value != nil {
		return ca.SetMemory(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdate) SetNotNilDisk(value *string) *CmdbAssetsUpdate {
	if value != nil {
		return ca.SetDisk(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdateOne) SetNotNilDisk(value *string) *CmdbAssetsUpdateOne {
	if value != nil {
		return ca.SetDisk(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsCreate) SetNotNilDisk(value *string) *CmdbAssetsCreate {
	if value != nil {
		return ca.SetDisk(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdate) SetNotNilNetworkSpeed(value *string) *CmdbAssetsUpdate {
	if value != nil {
		return ca.SetNetworkSpeed(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdateOne) SetNotNilNetworkSpeed(value *string) *CmdbAssetsUpdateOne {
	if value != nil {
		return ca.SetNetworkSpeed(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsCreate) SetNotNilNetworkSpeed(value *string) *CmdbAssetsCreate {
	if value != nil {
		return ca.SetNetworkSpeed(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdate) SetNotNilDeviceAddress(value *string) *CmdbAssetsUpdate {
	if value != nil {
		return ca.SetDeviceAddress(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsUpdateOne) SetNotNilDeviceAddress(value *string) *CmdbAssetsUpdateOne {
	if value != nil {
		return ca.SetDeviceAddress(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ca *CmdbAssetsCreate) SetNotNilDeviceAddress(value *string) *CmdbAssetsCreate {
	if value != nil {
		return ca.SetDeviceAddress(*value)
	}
	return ca
}

// set field if value's pointer is not nil.
func (ci *CmdbIpUpdate) SetNotNilUpdatedAt(value *time.Time) *CmdbIpUpdate {
	if value != nil {
		return ci.SetUpdatedAt(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpUpdateOne) SetNotNilUpdatedAt(value *time.Time) *CmdbIpUpdateOne {
	if value != nil {
		return ci.SetUpdatedAt(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpCreate) SetNotNilUpdatedAt(value *time.Time) *CmdbIpCreate {
	if value != nil {
		return ci.SetUpdatedAt(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpUpdate) SetNotNilUser(value *string) *CmdbIpUpdate {
	if value != nil {
		return ci.SetUser(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpUpdateOne) SetNotNilUser(value *string) *CmdbIpUpdateOne {
	if value != nil {
		return ci.SetUser(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpCreate) SetNotNilUser(value *string) *CmdbIpCreate {
	if value != nil {
		return ci.SetUser(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpUpdate) SetNotNilDepartment(value *string) *CmdbIpUpdate {
	if value != nil {
		return ci.SetDepartment(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpUpdateOne) SetNotNilDepartment(value *string) *CmdbIpUpdateOne {
	if value != nil {
		return ci.SetDepartment(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpCreate) SetNotNilDepartment(value *string) *CmdbIpCreate {
	if value != nil {
		return ci.SetDepartment(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpUpdate) SetNotNilMobile(value *string) *CmdbIpUpdate {
	if value != nil {
		return ci.SetMobile(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpUpdateOne) SetNotNilMobile(value *string) *CmdbIpUpdateOne {
	if value != nil {
		return ci.SetMobile(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpCreate) SetNotNilMobile(value *string) *CmdbIpCreate {
	if value != nil {
		return ci.SetMobile(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpUpdate) SetNotNilRemark(value *string) *CmdbIpUpdate {
	if value != nil {
		return ci.SetRemark(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpUpdateOne) SetNotNilRemark(value *string) *CmdbIpUpdateOne {
	if value != nil {
		return ci.SetRemark(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpCreate) SetNotNilRemark(value *string) *CmdbIpCreate {
	if value != nil {
		return ci.SetRemark(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpUpdate) SetNotNilIP(value *string) *CmdbIpUpdate {
	if value != nil {
		return ci.SetIP(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpUpdateOne) SetNotNilIP(value *string) *CmdbIpUpdateOne {
	if value != nil {
		return ci.SetIP(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpCreate) SetNotNilIP(value *string) *CmdbIpCreate {
	if value != nil {
		return ci.SetIP(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpUpdate) SetNotNilMask(value *string) *CmdbIpUpdate {
	if value != nil {
		return ci.SetMask(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpUpdateOne) SetNotNilMask(value *string) *CmdbIpUpdateOne {
	if value != nil {
		return ci.SetMask(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpCreate) SetNotNilMask(value *string) *CmdbIpCreate {
	if value != nil {
		return ci.SetMask(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpUpdate) SetNotNilGateway(value *string) *CmdbIpUpdate {
	if value != nil {
		return ci.SetGateway(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpUpdateOne) SetNotNilGateway(value *string) *CmdbIpUpdateOne {
	if value != nil {
		return ci.SetGateway(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpCreate) SetNotNilGateway(value *string) *CmdbIpCreate {
	if value != nil {
		return ci.SetGateway(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpUpdate) SetNotNilOnlineTime(value *time.Time) *CmdbIpUpdate {
	if value != nil {
		return ci.SetOnlineTime(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpUpdateOne) SetNotNilOnlineTime(value *time.Time) *CmdbIpUpdateOne {
	if value != nil {
		return ci.SetOnlineTime(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpCreate) SetNotNilOnlineTime(value *time.Time) *CmdbIpCreate {
	if value != nil {
		return ci.SetOnlineTime(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpUpdate) SetNotNilOfflineTime(value *time.Time) *CmdbIpUpdate {
	if value != nil {
		return ci.SetOfflineTime(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpUpdateOne) SetNotNilOfflineTime(value *time.Time) *CmdbIpUpdateOne {
	if value != nil {
		return ci.SetOfflineTime(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpCreate) SetNotNilOfflineTime(value *time.Time) *CmdbIpCreate {
	if value != nil {
		return ci.SetOfflineTime(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpUpdate) SetNotNilIsLeisure(value *uint) *CmdbIpUpdate {
	if value != nil {
		return ci.SetIsLeisure(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpUpdateOne) SetNotNilIsLeisure(value *uint) *CmdbIpUpdateOne {
	if value != nil {
		return ci.SetIsLeisure(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpCreate) SetNotNilIsLeisure(value *uint) *CmdbIpCreate {
	if value != nil {
		return ci.SetIsLeisure(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpUpdate) SetNotNilDeviceType(value *string) *CmdbIpUpdate {
	if value != nil {
		return ci.SetDeviceType(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpUpdateOne) SetNotNilDeviceType(value *string) *CmdbIpUpdateOne {
	if value != nil {
		return ci.SetDeviceType(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ci *CmdbIpCreate) SetNotNilDeviceType(value *string) *CmdbIpCreate {
	if value != nil {
		return ci.SetDeviceType(*value)
	}
	return ci
}

// set field if value's pointer is not nil.
func (ciu *CmdbIpUserUpdate) SetNotNilStatus(value *uint8) *CmdbIpUserUpdate {
	if value != nil {
		return ciu.SetStatus(*value)
	}
	return ciu
}

// set field if value's pointer is not nil.
func (ciu *CmdbIpUserUpdateOne) SetNotNilStatus(value *uint8) *CmdbIpUserUpdateOne {
	if value != nil {
		return ciu.SetStatus(*value)
	}
	return ciu
}

// set field if value's pointer is not nil.
func (ciu *CmdbIpUserCreate) SetNotNilStatus(value *uint8) *CmdbIpUserCreate {
	if value != nil {
		return ciu.SetStatus(*value)
	}
	return ciu
}

// set field if value's pointer is not nil.
func (ciu *CmdbIpUserUpdate) SetNotNilUpdatedAt(value *time.Time) *CmdbIpUserUpdate {
	if value != nil {
		return ciu.SetUpdatedAt(*value)
	}
	return ciu
}

// set field if value's pointer is not nil.
func (ciu *CmdbIpUserUpdateOne) SetNotNilUpdatedAt(value *time.Time) *CmdbIpUserUpdateOne {
	if value != nil {
		return ciu.SetUpdatedAt(*value)
	}
	return ciu
}

// set field if value's pointer is not nil.
func (ciu *CmdbIpUserCreate) SetNotNilUpdatedAt(value *time.Time) *CmdbIpUserCreate {
	if value != nil {
		return ciu.SetUpdatedAt(*value)
	}
	return ciu
}

// set field if value's pointer is not nil.
func (ciu *CmdbIpUserUpdate) SetNotNilUser(value *string) *CmdbIpUserUpdate {
	if value != nil {
		return ciu.SetUser(*value)
	}
	return ciu
}

// set field if value's pointer is not nil.
func (ciu *CmdbIpUserUpdateOne) SetNotNilUser(value *string) *CmdbIpUserUpdateOne {
	if value != nil {
		return ciu.SetUser(*value)
	}
	return ciu
}

// set field if value's pointer is not nil.
func (ciu *CmdbIpUserCreate) SetNotNilUser(value *string) *CmdbIpUserCreate {
	if value != nil {
		return ciu.SetUser(*value)
	}
	return ciu
}

// set field if value's pointer is not nil.
func (ciu *CmdbIpUserUpdate) SetNotNilDepartment(value *string) *CmdbIpUserUpdate {
	if value != nil {
		return ciu.SetDepartment(*value)
	}
	return ciu
}

// set field if value's pointer is not nil.
func (ciu *CmdbIpUserUpdateOne) SetNotNilDepartment(value *string) *CmdbIpUserUpdateOne {
	if value != nil {
		return ciu.SetDepartment(*value)
	}
	return ciu
}

// set field if value's pointer is not nil.
func (ciu *CmdbIpUserCreate) SetNotNilDepartment(value *string) *CmdbIpUserCreate {
	if value != nil {
		return ciu.SetDepartment(*value)
	}
	return ciu
}

// set field if value's pointer is not nil.
func (ciu *CmdbIpUserUpdate) SetNotNilMobile(value *string) *CmdbIpUserUpdate {
	if value != nil {
		return ciu.SetMobile(*value)
	}
	return ciu
}

// set field if value's pointer is not nil.
func (ciu *CmdbIpUserUpdateOne) SetNotNilMobile(value *string) *CmdbIpUserUpdateOne {
	if value != nil {
		return ciu.SetMobile(*value)
	}
	return ciu
}

// set field if value's pointer is not nil.
func (ciu *CmdbIpUserCreate) SetNotNilMobile(value *string) *CmdbIpUserCreate {
	if value != nil {
		return ciu.SetMobile(*value)
	}
	return ciu
}

// set field if value's pointer is not nil.
func (ciu *CmdbIpUserUpdate) SetNotNilRemark(value *string) *CmdbIpUserUpdate {
	if value != nil {
		return ciu.SetRemark(*value)
	}
	return ciu
}

// set field if value's pointer is not nil.
func (ciu *CmdbIpUserUpdateOne) SetNotNilRemark(value *string) *CmdbIpUserUpdateOne {
	if value != nil {
		return ciu.SetRemark(*value)
	}
	return ciu
}

// set field if value's pointer is not nil.
func (ciu *CmdbIpUserCreate) SetNotNilRemark(value *string) *CmdbIpUserCreate {
	if value != nil {
		return ciu.SetRemark(*value)
	}
	return ciu
}
