// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Cmdb is the predicate function for cmdb builders.
type Cmdb func(*sql.Selector)

// CmdbAssets is the predicate function for cmdbassets builders.
type CmdbAssets func(*sql.Selector)

// CmdbIp is the predicate function for cmdbip builders.
type CmdbIp func(*sql.Selector)

// CmdbIpUser is the predicate function for cmdbipuser builders.
type CmdbIpUser func(*sql.Selector)
